export type ExerciseGuide = {
  id: string; name: string; equipment: string; setup: string[]; movement: string[]; breathing: string; tempo: string; mistakes: string[]; safety: string[];
};

export const EXERCISE_GUIDES: ExerciseGuide[] = [
  { id: "pull-up", name: "Klimmzüge", equipment: "Klimmzugstation", setup: ["Stange etwas weiter als schulterbreit greifen.", "Schultern aktiv nach unten ziehen, Rumpf und Gesäß anspannen."], movement: ["Brust kontrolliert zur Stange führen.", "Ellbogen nach unten und hinten ziehen.", "Langsam bis fast gestreckte Arme absenken."], breathing: "Beim Hochziehen ausatmen, beim Absenken einatmen.", tempo: "2 Sekunden hoch, kurz stabilisieren, 3 Sekunden absenken.", mistakes: ["Schwingen oder Schwung aus den Beinen", "Schultern zu den Ohren ziehen", "Unkontrolliert in die Gelenke fallen"], safety: ["Bei Schulter- oder Ellbogenschmerz sofort abbrechen.", "Kinder nur kontrolliert und nicht bis zum Muskelversagen trainieren."] },
  { id: "push-up", name: "Liegestütze", equipment: "Klimmzugstation", setup: ["Hände stabil und etwa schulterbreit aufsetzen.", "Kopf, Rumpf und Beine bilden eine gerade Linie."], movement: ["Brust kontrolliert Richtung Auflage senken.", "Ellbogen ungefähr 30–45 Grad am Körper führen.", "Den Boden kräftig wegdrücken, ohne ins Hohlkreuz zu fallen."], breathing: "Beim Absenken einatmen, beim Hochdrücken ausatmen.", tempo: "3 Sekunden absenken, 1 Sekunde hochdrücken.", mistakes: ["Durchhängende Hüfte", "Vorgeschobener Kopf", "Zu weit abgespreizte Ellbogen"], safety: ["Leichtere Variante mit höherer Handposition wählen."] },
  { id: "sit-up", name: "Sit-ups", equipment: "Klimmzugstation", setup: ["Füße sicher fixieren, Knie beugen.", "Bauch anspannen und Nacken neutral halten."], movement: ["Oberkörper mit der Bauchmuskulatur anheben.", "Nur so weit aufrichten, wie der Rücken kontrolliert bleibt.", "Wirbel für Wirbel absenken."], breathing: "Beim Aufrichten ausatmen, beim Absenken einatmen.", tempo: "Ruhig und ohne Schwung.", mistakes: ["Am Nacken ziehen", "Mit Schwung starten", "Hohlkreuz beim Absenken"], safety: ["Bei Rücken- oder Nackenschmerz abbrechen; Crunch-Variante bevorzugen."] },
  { id: "leg-raise", name: "Hängendes Beinheben", equipment: "Klimmzugstation", setup: ["Sicher greifen oder Unterarme stabil auflegen.", "Schultern aktiv nach unten ziehen und Rumpf anspannen."], movement: ["Knie kontrolliert Richtung Brust führen.", "Becken leicht einrollen.", "Beine langsam ohne Pendeln absenken."], breathing: "Beim Anheben ausatmen, beim Absenken einatmen.", tempo: "2 Sekunden anheben, 3 Sekunden absenken.", mistakes: ["Pendeln", "Schultern hochziehen", "Beine fallen lassen"], safety: ["Zuerst mit gebeugten Knien arbeiten.", "Griff rechtzeitig lösen, bevor er versagt."] },
  { id: "butterfly", name: "Butterfly", equipment: "Kraftstation", setup: ["Sitz so einstellen, dass Griffe auf Brusthöhe liegen.", "Rücken und Kopf anlehnen, Füße stabil aufstellen."], movement: ["Arme in einem kontrollierten Bogen zusammenführen.", "Brust kurz anspannen, Schultern unten lassen.", "Langsam bis zur angenehmen Dehnung öffnen."], breathing: "Beim Schließen ausatmen, beim Öffnen einatmen.", tempo: "2 Sekunden schließen, 3 Sekunden öffnen.", mistakes: ["Zu hohes Gewicht", "Schultern nach vorne ziehen", "Gewichtsstapel aufschlagen lassen"], safety: ["Keine aggressive Dehnung hinter die Körperlinie.", "Gewicht für Kinder besonders leicht wählen."] },
  { id: "lat-pulldown", name: "Latzug", equipment: "Kraftstation", setup: ["Oberschenkelpolster sicher einstellen.", "Stange etwas weiter als schulterbreit greifen, Brustbein anheben."], movement: ["Stange vor dem Körper Richtung oberer Brust ziehen.", "Ellbogen nach unten führen, nicht nach hinten reißen.", "Arme kontrolliert strecken."], breathing: "Beim Herunterziehen ausatmen, beim Hochführen einatmen.", tempo: "2 Sekunden ziehen, 3 Sekunden zurückführen.", mistakes: ["Stange hinter den Nacken ziehen", "Stark nach hinten lehnen", "Schwung aus dem Oberkörper"], safety: ["Nie hinter den Kopf ziehen.", "Gewichte nur bei stillstehendem Stapel umstecken."] },
  { id: "treadmill", name: "Laufband", equipment: "Laufband", setup: ["Schnürsenkel prüfen und Sicherheitsclip befestigen.", "Seitlich aufsteigen und Band langsam starten."], movement: ["Aufrecht und mittig laufen, Blick nach vorne.", "Kurze natürliche Schritte verwenden.", "Geschwindigkeit langsam verändern."], breathing: "Gleichmäßig atmen; bei moderatem Tempo sollte Sprechen möglich bleiben.", tempo: "Mit 5–10 Minuten lockerem Aufwärmen beginnen und langsam auslaufen.", mistakes: ["Dauerhaft am Griff festhalten", "Zu weit hinten laufen", "Abrupte Geschwindigkeitswechsel"], safety: ["Kinder nur unter Aufsicht.", "Bei Schwindel Not-Stopp verwenden und sicher absteigen."] },
  { id: "vibration", name: "Vibrationsplatte", equipment: "Vibrationsplatte", setup: ["Stabil und mittig stehen, Knie leicht beugen.", "Mit niedriger Stufe und kurzer Dauer beginnen."], movement: ["Gelenke weich halten und Position kontrollieren.", "Bei Übungen langsam und ohne Zusatzschwung arbeiten."], breathing: "Ruhig weiteratmen, nicht pressen.", tempo: "Kurze Intervalle nach Herstellerangabe.", mistakes: ["Durchgedrückte Knie", "Zu hohe Intensität", "Lange ungewohnte Belastung"], safety: ["Herstellerhinweise und medizinische Gegenanzeigen beachten.", "Bei Unwohlsein sofort ausschalten."] },
  { id: "punchbag", name: "Boxsack", equipment: "Boxsack", setup: ["Bandagen und passende Handschuhe verwenden.", "Stabiler Stand, Hände am Kopf, Handgelenke gerade."], movement: ["Schläge aus Körperdrehung und Beinarbeit führen.", "Arm nicht vollständig durchschlagen.", "Hand nach jedem Schlag zur Deckung zurückbringen."], breathing: "Bei jedem Schlag kurz ausatmen.", tempo: "Technik vor Härte; kurze Runden mit Pausen.", mistakes: ["Abgeknickte Handgelenke", "Maximalkraft ohne Aufwärmen", "Deckung fallen lassen"], safety: ["Sackaufhängung regelmäßig prüfen.", "Kinder trainieren Technik und Kontrolle, nicht maximale Schlaghärte."] },
  { id: "bike", name: "Fahrrad", equipment: "Fahrrad", setup: ["Sattelhöhe so wählen, dass das Knie unten leicht gebeugt bleibt.", "Füße sicher auf Pedalen platzieren."], movement: ["Rund und gleichmäßig treten.", "Oberkörper ruhig und Schultern locker halten.", "Widerstand schrittweise verändern."], breathing: "Gleichmäßig atmen; bei moderatem Tempo sollte Sprechen möglich sein.", tempo: "5–10 Minuten aufwärmen, danach Hauptteil und ruhiges Ausfahren.", mistakes: ["Zu niedriger Sattel", "Zu hoher Widerstand bei niedriger Trittfrequenz", "Verkrampfte Schultern"], safety: ["Bei Knieschmerz Einstellung und Widerstand prüfen."] }
];

export function getExerciseGuide(id: string) { return EXERCISE_GUIDES.find((guide) => guide.id === id); }
