import { expect, it, vi } from "vitest";
import { spawnSync } from "node:child_process";
import { buildEnergyShortcut, energyInstaller, plist } from "./health-shortcut";
import { GET } from "@/app/api/admin/health-shortcut/route";

const auth = vi.hoisted(() => ({ reject: false }));
vi.mock("./security", () => ({ verifyAdminPinOrReject: async () => auth.reject ? new Response("Unauthorized", { status: 401 }) : null }));
vi.mock("./db", () => ({ db: async () => ({ execute: async ({ args }: { args: string[] }) => ({ rows: args[0] === "papa" ? [{ id: "papa" }] : [] }) }) }));
vi.mock("./server-url", () => ({ getMobileReachableBaseUrl: () => "http://192.168.1.253:3000" }));

it("builds a complete text-only energy workflow without the looping import dialog", () => {
  const shortcut = buildEnergyShortcut("papa", "http://192.168.1.253:3000");
  const actions = shortcut.WFWorkflowActions as { WFWorkflowActionIdentifier: string; WFWorkflowActionParameters: Record<string, unknown> }[];
  const identifiers = actions.map(action => action.WFWorkflowActionIdentifier);
  expect(identifiers).not.toContain("is.workflow.actions.math");
  expect(identifiers).not.toContain("is.workflow.actions.statistics");
  const combine = actions.find(action => action.WFWorkflowActionIdentifier === "is.workflow.actions.text.combine")!;
  expect(combine.WFWorkflowActionParameters.text).toMatchObject({ WFSerializationType: "WFTextTokenAttachment", Value: { Type: "Variable", VariableName: "Energiezeilen" } });
  expect(identifiers).not.toContain("is.workflow.actions.conditional");
  expect(identifiers).not.toContain("is.workflow.actions.exit");
  expect(identifiers).toContain("is.workflow.actions.showresult");
  expect(actions.filter(action => action.WFWorkflowActionIdentifier === "is.workflow.actions.appendvariable").map(action => action.WFWorkflowActionParameters.WFVariableName)).toEqual(["Energiezeilen", "Schrittzeilen", "Trainingsminutenzeilen"]);
  expect(combine.WFWorkflowActionParameters.WFInput).toBeUndefined();
  expect(shortcut.WFWorkflowImportQuestions).toEqual([]);
  expect(actions[1].WFWorkflowActionParameters.WFTextActionText).toBe("FAMILIENSCHLUESSEL_HIER_EINFUEGEN");
  expect(actions[2].WFWorkflowActionParameters.WFTextActionText).toBe("EXAKTEN_HEALTH_DATENQUELLENNAMEN_EINFUEGEN");
  const uuids = new Set(actions.map(action => action.WFWorkflowActionParameters.UUID));
  for (const match of JSON.stringify(shortcut).matchAll(/"OutputUUID":"([^"]+)"/g)) expect(uuids.has(match[1])).toBe(true);
  expect(JSON.stringify(shortcut)).toContain("/api/sync/health-energy/bulk");
  expect(shortcut.WFWorkflowName).toBe("FitFamily Alltag v5 · papa");
  expect(JSON.stringify(shortcut)).toContain("Startdatum innerhalb der letzten 30 Tage");
  expect(JSON.stringify(shortcut)).toContain('"Number":"30"');
  expect(actions.filter(action => action.WFWorkflowActionIdentifier === "is.workflow.actions.filter.health.quantity").every(action => JSON.stringify(action.WFWorkflowActionParameters).includes('"Operator":1001'))).toBe(true);
  expect(JSON.stringify(shortcut)).toContain("Bearer ");
  expect(JSON.stringify(shortcut)).toContain("Exercise Minutes");
  expect(JSON.stringify(shortcut)).not.toContain("stepCount");
  expect(JSON.stringify(shortcut)).toContain("stepRows");
  expect(JSON.stringify(shortcut)).toContain("trainingRows");
  expect(JSON.stringify(shortcut)).toContain('"Value":"Steps"');
  expect(actions.filter(action => action.WFWorkflowActionIdentifier === "is.workflow.actions.text.combine")).toHaveLength(3);
  expect(plist("<&\"")).toBe("<string>&lt;&amp;&quot;</string>");
});
it("rejects injection and builds a self-contained Mac installer with no real secret", () => {
  for (const server of ["http://0.0.0.0:3000", "http://localhost:3000", "http://127.0.0.1:3000", "http://[::]:3000", "http://[::1]:3000", "https://a/b", "file:///tmp/evil", "https://user:pass@example.com", "https://a/?key=x"]) expect(() => energyInstaller("papa", server)).toThrow();
  expect(() => energyInstaller("papa;touch x", "https://example.com")).toThrow();
  const installer = energyInstaller("papa", "https://example.com");
  expect(installer).toContain("shortcuts sign --mode anyone");
  expect(installer).toContain("/usr/bin/open");
  expect(installer).not.toContain("npm");
  expect(spawnSync("bash", ["-n"], { input: installer }).status).toBe(0);
  const base64 = installer.match(/echo '([A-Za-z0-9+/=]+)' \|/)!;
  const xml = Buffer.from(base64[1], "base64").toString();
  expect(xml).toContain("FAMILIENSCHLUESSEL_HIER_EINFUEGEN");
  expect(xml).toContain("EXAKTEN_HEALTH_DATENQUELLENNAMEN_EINFUEGEN");
  if (process.platform === "darwin") expect(spawnSync("/usr/bin/plutil", ["-lint", "-"], { input: xml }).status).toBe(0);
});
it("serves an authenticated downloadable installer for an existing profile only", async () => {
  auth.reject = true;
  expect((await GET(new Request("http://localhost/api/admin/health-shortcut?profileId=papa"))).status).toBe(401);
  auth.reject = false;
  expect((await GET(new Request("http://localhost/api/admin/health-shortcut?profileId=missing"))).status).toBe(404);
  expect((await GET(new Request("http://localhost/api/admin/health-shortcut?profileId=papa&server=file:///tmp/x"))).status).toBe(400);
  const result = await GET(new Request("http://localhost/api/admin/health-shortcut?profileId=papa&server=https://example.com"));
  expect(result.status).toBe(200);
  expect(result.headers.get("content-disposition")).toContain(".command");
  expect(result.headers.get("cache-control")).toBe("no-store");
  expect(await result.text()).toContain("#!/bin/bash");
  const app = await GET(new Request("http://localhost/api/admin/health-shortcut?profileId=papa&server=https://example.com&format=app"));
  expect(app.status).toBe(200);
  expect(app.headers.get("content-type")).toBe("application/zip");
  expect(app.headers.get("content-disposition")).toContain(".zip");
  expect(new Uint8Array(await app.arrayBuffer()).slice(0, 4)).toEqual(new Uint8Array([80, 75, 3, 4]));
  const automatic = await GET(new Request("http://0.0.0.0:3000/api/admin/health-shortcut?profileId=papa"));
  expect(automatic.status).toBe(200);
  const script = await automatic.text();
  const payload = script.match(/echo '([A-Za-z0-9+/=]+)' \|/)!;
  expect(Buffer.from(payload[1], "base64").toString()).toContain("http://192.168.1.253:3000/api/sync/health-energy/bulk");
  expect((await GET(new Request("http://localhost/api/admin/health-shortcut?profileId=papa&server=http://0.0.0.0:3000"))).status).toBe(400);
});
